

service: data-collector

provider:
  name: aws
  runtime: python3.7
  profile: andrea.soriano
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"


functions:
  dataCollector:
    handler: handler.dataCollector
